# --- !Ups
create table "OPERATION" (
  "ID" bigint generated by default as identity(start with 1) not null primary key,
  "DATE" timestamp default current_timestamp,
  "NATURE" varchar not null,
  "AMOUNT" DOUBLE not null,
  "TOTAL" DOUBLE not null,
  "ACCOUNT_ID" bigint,
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(id)
);
# --- !Downs

drop table "operation" if exists;
