services: docker


before_install:
  - docker -v
  # Use the env config
  - cp .env.example .env
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop
  # set env vars in the build settings to interact with repositories

install:
  # Start the docker stuff
  - docker-compose up -d
  - sleep 10
script:
  - docker-compose exec web sh -c "sbt test"
after_script:
  - docker-compose stop
  - docker-compose rm -f