version: '3'
services:
  web:
    depends_on:
      - db
    links:
      - db
    build: .
    restart: 'always'
    ports:
      - "9100:9000"
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: scalabank
      MYSQL_DATABASE: bank
    ports:
      - 3306:3306
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080